version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carauction_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - carauction_network

networks:
  carauction_network:
    name: carauction_network
    external: true
